name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ DOCKERHUB_USERNAME }}
        password: ${{ DOCKERHUB_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build -t electricity_prices .
        docker push 
    
    - name: Check CI success
      run: |
        # check CI success
    
  deploy_to_kubernetes:
    needs: build_and_push_image
    runs-on: ubuntu-latest
    if: success()
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ DOCKERHUB_USERNAME }}
        password: ${{ DOCKERHUB_PASSWORD }}
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f app-deployment.yaml